project_id = "bkbcqocpjahewqjmlgvf"

[api]
enabled = true
port = 54321

[db] 
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54324

[functions]

[functions.authorize]
verify_jwt = false

[functions.admin-organizations]
verify_jwt = true

[functions.app-store-scraper]
verify_jwt = false

[functions.admin-features]
verify_jwt = true