project_id = "bkbcqocpjahewqjmlgvf"

[api]
enabled = true
port = 54321

[db] 
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54324

[functions]

[functions.admin-organizations]
verify_jwt = true