#!/bin/bash

echo "🔑 Quick Seed Script"
echo "═══════════════════════════════════════════════════"
echo ""
echo "To seed the database, you need your Supabase SERVICE ROLE key."
echo ""
echo "📋 Steps:"
echo ""
echo "1. Get your service role key:"
echo "   https://supabase.com/dashboard/project/bkbcqocpjahewqjmlgvf/settings/api"
echo ""
echo "2. Look for 'service_role' (not 'anon' key) and copy it"
echo ""
echo "3. Run this command (replace YOUR_KEY with the actual key):"
echo ""
echo "   SUPABASE_SERVICE_ROLE_KEY='YOUR_KEY' node scripts/seed-yodel-mobile.mjs"
echo ""
echo "Example:"
echo "   SUPABASE_SERVICE_ROLE_KEY='eyJhbGci...xyz' node scripts/seed-yodel-mobile.mjs"
echo ""
echo "═══════════════════════════════════════════════════"
