/**
 * KPI Definitions & User-Friendly Explanations
 *
 * User-facing explanations for all metadata audit KPIs.
 * Used for tooltips, help dialogs, and documentation.
 *
 * Format:
 * - title: Display name
 * - shortDesc: One-line summary (for tooltips)
 * - longDesc: Detailed explanation (for help dialogs)
 * - whatItMeans: What the score/gap indicates
 * - howToImprove: Actionable guidance
 */

export interface KpiDefinition {
  id: string;
  title: string;
  shortDesc: string;
  longDesc: string;
  whatItMeans: {
    high: string;  // Score 80-100
    medium: string; // Score 50-79
    low: string;    // Score 0-49
  };
  howToImprove: string[];
  category: 'overall' | 'coverage' | 'intent' | 'structure' | 'quality';
}

// ============================================================================
// High-Level Metadata Dimensions (shown in charts)
// ============================================================================

export const METADATA_DIMENSION_DEFINITIONS: Record<string, KpiDefinition> = {
  intent_coverage: {
    id: 'intent_coverage',
    title: 'Intent Coverage',
    shortDesc: 'How well your metadata covers user search intents (informational, commercial, transactional)',
    longDesc: 'Intent Coverage measures how comprehensively your title, subtitle, and description address different types of user search queries. Search intent falls into three categories: informational (learning/discovery), commercial (comparison/evaluation), and transactional (ready to download). High coverage means your metadata speaks to users at all stages of the decision journey.',
    whatItMeans: {
      high: 'Your metadata addresses multiple search intents effectively. Users at different stages of the decision journey will find relevant information.',
      medium: 'Your metadata covers some intents but misses opportunities to connect with users in other stages. Consider broadening your appeal.',
      low: 'Your metadata focuses too narrowly on one intent type. You\'re missing users who search with different goals (e.g., learning vs. buying).',
    },
    howToImprove: [
      'Add informational keywords (learn, guide, tutorial) to attract discovery searches',
      'Include commercial keywords (best, vs, compare) for evaluation stage users',
      'Use transactional keywords (free, download, get) for ready-to-install users',
      'Balance all three intent types to maximize reach across the decision funnel',
    ],
    category: 'intent',
  },

  keyword_coverage: {
    id: 'keyword_coverage',
    title: 'Keyword Coverage',
    shortDesc: 'Percentage of high-value keywords included in your metadata',
    longDesc: 'Keyword Coverage measures how many relevant, high-traffic keywords from your category are present in your title, subtitle, and description. This metric is calculated by analyzing top-performing apps in your vertical and identifying must-have keywords, then checking how many you\'ve included. Higher coverage means better discoverability.',
    whatItMeans: {
      high: 'You\'ve included most critical keywords for your category. Your app is discoverable for key search terms.',
      medium: 'You\'re covering some important keywords but missing opportunities. Competitors may outrank you for certain searches.',
      low: 'You\'re missing many high-value keywords. Your app is hard to discover organically and you\'re leaving traffic on the table.',
    },
    howToImprove: [
      'Research top apps in your category to identify must-have keywords',
      'Prioritize keywords with high search volume and low competition',
      'Include category-defining terms (e.g., "language learning" for edu apps)',
      'Add long-tail variations to capture niche searches',
      'Avoid keyword stuffing - focus on natural, readable integration',
    ],
    category: 'coverage',
  },

  combo_quality: {
    id: 'combo_quality',
    title: 'Combo Quality',
    shortDesc: 'Quality and diversity of keyword combinations in your metadata',
    longDesc: 'Combo Quality evaluates the keyword combinations (2-3 word phrases) generated by your metadata. High-quality combos are specific, searchable phrases that match real user queries (e.g., "learn spanish kids" vs. "best app"). This metric considers combo relevance, search intent classification, and diversity across informational, commercial, and branded terms.',
    whatItMeans: {
      high: 'Your metadata generates many high-quality, searchable phrases. You\'re capturing specific, intent-rich queries.',
      medium: 'You have some good combos but many are generic or low-value. You could be more targeted in your phrasing.',
      low: 'Your metadata produces mostly generic or nonsensical combos. You\'re not matching real user search patterns.',
    },
    howToImprove: [
      'Write metadata that naturally forms searchable phrases (not just keyword lists)',
      'Test phrase combinations - would users actually search for them?',
      'Avoid filler words that dilute combo quality (best, top, great)',
      'Create specific combos like "kids spanish lessons" instead of generic "best app"',
      'Balance branded combos (with your app name) and generic discovery combos',
    ],
    category: 'quality',
  },

  discovery_coverage: {
    id: 'discovery_coverage',
    title: 'Discovery Coverage',
    shortDesc: 'Percentage of metadata optimized for organic discovery (non-branded searches)',
    longDesc: 'Discovery Coverage measures how much of your metadata is dedicated to helping new users find your app through generic, category-related searches. This excludes branded terms (your app name) and focuses on keywords that attract users who don\'t know your brand yet. High discovery coverage means you\'re not overly reliant on brand awareness.',
    whatItMeans: {
      high: 'Your metadata is well-optimized for organic discovery. New users can find you through category searches.',
      medium: 'You have some discovery keywords but could expand further. You may be over-indexing on brand terms.',
      low: 'Your metadata is brand-heavy. Only users who already know your app name can find you. Growth is limited.',
    },
    howToImprove: [
      'Reduce repetition of your brand name - use it once or twice max',
      'Add category-defining keywords (e.g., "meditation app" not just "Headspace")',
      'Include use-case keywords (e.g., "sleep better", "reduce stress")',
      'Target competitor keywords where appropriate',
      'Focus subtitle and description on discovery, not brand reinforcement',
    ],
    category: 'coverage',
  },

  relevance: {
    id: 'relevance',
    title: 'Relevance',
    shortDesc: 'Semantic relevance of keywords to your app category and use cases',
    longDesc: 'Relevance measures how closely your keywords align with your app\'s core category and user needs. High-relevance keywords are those that users in your vertical actually search for. This is calculated by analyzing token-level relevance scores based on your detected category (e.g., "learn", "lesson" are highly relevant for education apps, but "game" is not).',
    whatItMeans: {
      high: 'Your keywords are tightly aligned with your category and user needs. You\'re attracting the right audience.',
      medium: 'Most keywords are relevant but some are generic or off-topic. You could be more focused.',
      low: 'Many keywords are low-relevance or off-category. You\'re attracting the wrong users or getting low conversion.',
    },
    howToImprove: [
      'Remove generic modifiers (best, top, new) - they add little relevance',
      'Focus on category-specific terminology (industry jargon users know)',
      'Include problem-solution keywords (what pain points do you solve?)',
      'Avoid trendy but irrelevant keywords just for traffic',
      'Test keywords against your target user persona - would they search for this?',
    ],
    category: 'quality',
  },

  structure: {
    id: 'structure',
    title: 'Structure',
    shortDesc: 'Optimal use of character limits, readability, and metadata organization',
    longDesc: 'Structure evaluates how well you\'ve organized and formatted your metadata. This includes character limit utilization (iOS: 30-char title, 30-char subtitle; Android: 50-char title, 80-char subtitle), word count balance, readability, and presence of key structural elements like feature bullets and clear sections in descriptions.',
    whatItMeans: {
      high: 'Your metadata is well-structured, readable, and makes full use of available space. Professional presentation.',
      medium: 'Structure is adequate but you\'re leaving space unused or have readability issues. Some improvements possible.',
      low: 'Metadata is poorly structured - too short, too long, hard to read, or disorganized. Users and algorithms struggle to parse it.',
    },
    howToImprove: [
      'Use 80-95% of character limits (don\'t waste space, but don\'t cram)',
      'Keep title to 3-5 words for readability',
      'Keep subtitle to 4-6 words for optimal coverage without crowding',
      'Structure descriptions with clear sections: features, benefits, use cases',
      'Use bullet points or line breaks for easy scanning',
      'Avoid all-caps, emoji overload, or excessive punctuation',
    ],
    category: 'structure',
  },

  brand_balance: {
    id: 'brand_balance',
    title: 'Brand Balance',
    shortDesc: 'Optimal ratio of branded vs. generic discovery keywords',
    longDesc: 'Brand Balance measures whether you\'ve struck the right balance between brand reinforcement and discovery optimization. The ideal ratio is 10-25% branded terms. Too little brand presence can hurt existing user retention; too much brand presence limits new user acquisition. This metric helps you find the sweet spot.',
    whatItMeans: {
      high: 'Perfect balance - enough brand presence for recognition, enough generic terms for discovery. Optimal for growth.',
      medium: 'Brand ratio is slightly off - either over-branded (limiting discovery) or under-branded (losing identity).',
      low: 'Serious imbalance - either brand-stuffed (only existing users can find you) or brand-absent (no identity/recognition).',
    },
    howToImprove: [
      'Aim for 10-25% brand terms (1-2 mentions in title/subtitle combined)',
      'If over-branded: Remove repetitive brand mentions, replace with features',
      'If under-branded: Add brand name once in title or subtitle for recognition',
      'Use brand strategically in combos (e.g., "Duolingo Spanish" not "Duolingo by Duolingo")',
      'Reserve brand-heavy content for screenshots and videos, not metadata',
    ],
    category: 'quality',
  },
};

// ============================================================================
// Gap Interpretation Helper
// ============================================================================

/**
 * Explain what a gap (delta from 100) means for a given metric
 */
export function explainGap(metricId: string, currentScore: number): string {
  const gap = 100 - currentScore;
  const def = getDefinition(metricId);

  if (!def) {
    return `Your ${metricId} score is ${currentScore}/100. You have a ${gap}-point gap to perfect optimization.`;
  }

  let severity = '';
  let impact = '';

  if (gap >= 40) {
    severity = 'critical';
    impact = 'This is a high-impact improvement opportunity that could significantly boost your discoverability.';
  } else if (gap >= 25) {
    severity = 'significant';
    impact = 'This is a strong improvement opportunity that would meaningfully enhance your metadata.';
  } else if (gap >= 15) {
    severity = 'moderate';
    impact = 'This is a moderate improvement opportunity worth addressing in your next optimization pass.';
  } else {
    severity = 'minor';
    impact = 'This is a minor refinement opportunity. Your score is already strong.';
  }

  return `**${def.title}: ${currentScore}/100 (${gap}-point gap)**\n\nThis is a ${severity} gap. ${impact}\n\n**What this score means:**\n${currentScore >= 80 ? def.whatItMeans.high : currentScore >= 50 ? def.whatItMeans.medium : def.whatItMeans.low}`;
}

/**
 * Get improvement suggestions for a metric
 */
export function getImprovementSuggestions(metricId: string): string[] {
  const def = METADATA_DIMENSION_DEFINITIONS[metricId];
  return def?.howToImprove || [];
}

/**
 * Get short tooltip text for a metric
 */
export function getTooltipText(metricId: string): string {
  const def = getDefinition(metricId);
  return def?.shortDesc || '';
}

/**
 * Get full explanation for a metric
 */
export function getFullExplanation(metricId: string): string {
  const def = getDefinition(metricId);
  if (!def) return '';

  return `${def.title}\n\n${def.longDesc}\n\nHow to improve:\n${def.howToImprove.map(tip => `• ${tip}`).join('\n')}`;
}

// ============================================================================
// Search Intent Type Definitions (for DiscoveryFootprintMap)
// ============================================================================

export const INTENT_TYPE_DEFINITIONS: Record<string, KpiDefinition> = {
  informational_intent: {
    id: 'informational_intent',
    title: 'Informational Intent',
    shortDesc: 'Discovery searches where users are learning about a topic or exploring options',
    longDesc: 'Informational intent captures searches where users are in the early discovery phase. They\'re researching, learning, and exploring options. These searches typically include question words (how, what, why), learning verbs (learn, understand, guide), or topic exploration terms. High informational coverage attracts top-of-funnel users who don\'t know your brand yet.',
    whatItMeans: {
      high: 'You\'re capturing discovery traffic effectively. New users can find you through educational searches.',
      medium: 'You have some informational keywords but could expand to capture more discovery traffic.',
      low: 'You\'re missing discovery opportunities. Users in research mode won\'t find you.',
    },
    howToImprove: [
      'Add question-based keywords: "how to", "what is", "guide to"',
      'Include learning verbs: "learn", "understand", "discover", "explore"',
      'Use tutorial language: "beginner guide", "step by step", "tutorial"',
      'Add educational terms: "tips", "tricks", "lessons", "course"',
      'Focus on problem-awareness stage: "why you need", "benefits of"',
    ],
    category: 'intent',
  },

  outcome_intent: {
    id: 'outcome_intent',
    title: 'Outcome Intent',
    shortDesc: 'Result-focused searches where users want to achieve a specific goal or transformation',
    longDesc: 'Outcome intent represents searches where users are goal-oriented and want to achieve a specific result. These searches focus on end states, transformations, or achievements rather than the process. Keywords include achievement verbs (get, achieve, become, master), result nouns (fluency, confidence, success), and goal phrases. High outcome coverage attracts motivated users.',
    whatItMeans: {
      high: 'You\'re effectively communicating the transformations and results users can achieve.',
      medium: 'You mention some outcomes but could be more explicit about end results.',
      low: 'You\'re not clearly communicating what users will achieve. Focus more on results.',
    },
    howToImprove: [
      'Use achievement verbs: "achieve", "master", "become", "reach", "attain"',
      'Include transformation language: "get fluent", "speak confidently", "lose weight"',
      'Focus on end states: "fluency", "mastery", "success", "proficiency"',
      'Add time-bound goals: "in 30 days", "quickly", "fast results"',
      'Emphasize benefits: "confidence", "freedom", "capability"',
    ],
    category: 'intent',
  },

  generic_intent: {
    id: 'generic_intent',
    title: 'Generic Intent',
    shortDesc: 'Broad category searches without specific brand or deep intent signals',
    longDesc: 'Generic intent covers broad category-level searches where users are exploring a category but haven\'t narrowed to specific features or brands. These are high-volume, competitive searches like "meditation app", "language learning", or "fitness tracker". While competitive, these searches are essential for category visibility and reaching users who haven\'t formed preferences yet.',
    whatItMeans: {
      high: 'Strong category visibility. You\'re competing for broad, high-volume searches.',
      medium: 'You have some category terms but could be more explicit.',
      low: 'Weak category presence. Users searching broadly won\'t find you.',
    },
    howToImprove: [
      'Include category names: "meditation app", "language learning app", "fitness tracker"',
      'Add broad use cases: "for sleep", "for work", "for travel"',
      'Use generic descriptors: "mobile app", "tool", "platform", "solution"',
      'Include broad audience terms: "for beginners", "for everyone", "for adults"',
      'Balance with more specific terms to avoid being too generic',
    ],
    category: 'intent',
  },

  brand_intent: {
    id: 'brand_intent',
    title: 'Brand Intent',
    shortDesc: 'Branded searches where users specifically look for your app by name',
    longDesc: 'Brand intent represents searches that include your app name or brand. These are high-intent, high-conversion searches from users who already know your brand. While important for capturing existing awareness, over-optimization for brand searches limits discovery of new users. Ideal brand ratio is 10-25% of your metadata to balance recognition with discovery.',
    whatItMeans: {
      high: 'Strong brand presence, but ensure you\'re not sacrificing discovery keywords.',
      medium: 'Balanced brand visibility - good for recognition without limiting discovery.',
      low: 'Weak brand presence. Users who know your name might not find you easily.',
    },
    howToImprove: [
      'Include brand name 1-2 times in title/subtitle (not more)',
      'Create branded combos: "Duolingo Spanish" not "Duolingo by Duolingo"',
      'Use brand strategically in description for context',
      'Don\'t sacrifice discovery keywords for brand repetition',
      'Remember: branded searches will find you anyway - optimize for discovery',
    ],
    category: 'intent',
  },

  low_value_intent: {
    id: 'low_value_intent',
    title: 'Low-Value Intent',
    shortDesc: 'Generic modifiers and filler words that add little search value',
    longDesc: 'Low-value intent includes generic superlatives, temporal modifiers, and filler words that don\'t help with discovery or conversion. Words like "best", "top", "new", "great", "amazing" are overused, don\'t differentiate you, and waste valuable character space. These terms have low relevance scores and should be minimized in favor of specific, meaningful keywords.',
    whatItMeans: {
      high: 'Too many filler words. You\'re wasting space on non-specific modifiers.',
      medium: 'Some filler present but not excessive. Could trim for better keywords.',
      low: 'Minimal filler - good! You\'re using space efficiently for meaningful keywords.',
    },
    howToImprove: [
      'Remove generic superlatives: "best", "top", "great", "amazing"',
      'Avoid temporal modifiers: "new", "latest", "modern"',
      'Cut promotional fluff: "premium", "pro", "ultimate"',
      'Replace with specific features: "40+ languages" not "best app"',
      'Use concrete benefits: "sleep better" not "great for sleep"',
    ],
    category: 'intent',
  },
};

// ============================================================================
// Token Type Definitions (for TokenMixDonut)
// ============================================================================

export const TOKEN_TYPE_DEFINITIONS: Record<string, KpiDefinition> = {
  high_value_token: {
    id: 'high_value_token',
    title: 'High-Value Tokens',
    shortDesc: 'Category-specific, highly relevant keywords with strong search intent (relevance = 3)',
    longDesc: 'High-value tokens are the most important keywords in your metadata. These are category-defining terms, core intent verbs, and language-specific words that users actively search for. For language apps, these include language names (Spanish, French) and core verbs (learn, speak, study). For fitness apps, these are workout types (yoga, HIIT) and goals (weight loss, muscle). Maximize these!',
    whatItMeans: {
      high: 'Excellent keyword selection! Your metadata is rich with category-specific, high-intent terms.',
      medium: 'Good mix of high-value keywords but room to add more category-specific terms.',
      low: 'Too few high-value keywords. Add more category-defining and intent-rich terms.',
    },
    howToImprove: [
      'Identify category-defining keywords for your vertical',
      'Include core action verbs users search for',
      'Add specific outcome terms (fluency, mastery, transformation)',
      'Use domain-specific jargon your audience knows',
      'Replace generic terms with category-specific alternatives',
    ],
    category: 'quality',
  },

  medium_value_token: {
    id: 'medium_value_token',
    title: 'Medium-Value Tokens',
    shortDesc: 'Domain-relevant supporting keywords that add context (relevance = 2)',
    longDesc: 'Medium-value tokens are solid supporting keywords that provide context and breadth. These include related concepts, feature names, method names, and supporting nouns. They\'re valuable but not as critical as high-value tokens. Examples: "lessons", "practice", "courses" for education apps, or "workouts", "training", "exercises" for fitness apps.',
    whatItMeans: {
      high: 'Good supporting keyword coverage. You\'re providing helpful context.',
      medium: 'Adequate supporting terms but could add more for better coverage.',
      low: 'Weak supporting vocabulary. Add more feature and method names.',
    },
    howToImprove: [
      'Add feature names: "lessons", "quizzes", "practice sessions"',
      'Include method names: "spaced repetition", "immersion", "guided meditation"',
      'Use supporting nouns: "courses", "tutorials", "exercises"',
      'Add modality terms: "audio", "video", "interactive"',
      'Include audience segments: "beginners", "advanced", "professionals"',
    ],
    category: 'quality',
  },

  low_value_token: {
    id: 'low_value_token',
    title: 'Low-Value Tokens',
    shortDesc: 'Generic modifiers and filler words with minimal search value (relevance = 0-1)',
    longDesc: 'Low-value tokens include generic superlatives (best, top, great), temporal modifiers (new, latest), and promotional fluff (premium, ultimate). These words don\'t help with discovery, don\'t differentiate you from competitors, and waste valuable character space. They should be minimized or eliminated entirely in favor of specific, meaningful keywords.',
    whatItMeans: {
      high: 'Too much filler! You\'re wasting space on generic modifiers instead of real keywords.',
      medium: 'Some filler present. Clean up generic terms to make room for better keywords.',
      low: 'Minimal filler - excellent! You\'re using character space efficiently.',
    },
    howToImprove: [
      'Remove "best", "top", "great", "amazing", "awesome"',
      'Cut "new", "latest", "modern", "innovative"',
      'Eliminate "premium", "pro", "ultimate", "perfect"',
      'Replace with specific features or quantifiable benefits',
      'Use concrete data: "40+ languages" not "many languages"',
    ],
    category: 'quality',
  },

  stopword: {
    id: 'stopword',
    title: 'Stopwords',
    shortDesc: 'Common filler words with zero SEO value (and, the, for, with, etc.)',
    longDesc: 'Stopwords are grammatical connectors and articles that are necessary for readability but have zero search value. Words like "and", "the", "for", "with", "of", "in" don\'t help with discovery but are essential for forming natural, readable phrases. The key is to minimize them while maintaining readability - aim for 20-30% stopwords maximum.',
    whatItMeans: {
      high: 'Excessive stopwords (>40%). Your metadata reads well but wastes SEO potential.',
      medium: 'Moderate stopwords (25-35%). Good balance of readability and efficiency.',
      low: 'Minimal stopwords (<20%). Maximum keyword density but may impact readability.',
    },
    howToImprove: [
      'Use stopwords only where necessary for readability',
      'Prefer compact phrasing: "Spanish Learning" vs "Learning of Spanish"',
      'Remove unnecessary articles: "Learn Languages" vs "Learn The Languages"',
      'Avoid excessive prepositions: "Yoga Workout Beginners" vs "Yoga Workout for Beginners"',
      'Balance keyword density with natural readability',
    ],
    category: 'structure',
  },
};

// ============================================================================
// Character Limit Definitions (for SlotUtilizationBars)
// ============================================================================

export const CHARACTER_LIMIT_DEFINITIONS: Record<string, KpiDefinition> = {
  title_char_usage: {
    id: 'title_char_usage',
    title: 'Title Character Usage',
    shortDesc: 'Percentage of title character limit used (iOS: 30 chars, Android: 50 chars)',
    longDesc: 'Title character usage measures how efficiently you\'re using the available character space for your app title. iOS allows 30 characters, Android allows 50. Optimal usage is 80-95% - using most of the space without cramming. Under-utilization wastes prime SEO real estate; over-utilization (hitting 100% exactly) suggests you might be cutting important words.',
    whatItMeans: {
      high: 'Excellent space utilization! You\'re making full use of available characters.',
      medium: 'Adequate usage but leaving some valuable space unused.',
      low: 'Significant wasted space. Your title is too short - add more keywords.',
    },
    howToImprove: [
      'Target 80-95% character usage (24-28 chars for iOS, 40-47 for Android)',
      'Don\'t waste space: "App" → "Language Learning App"',
      'Don\'t overstuff: Leave 2-3 chars buffer for natural endings',
      'Prioritize high-value keywords in limited space',
      'Test different phrasings to maximize keyword coverage within limits',
    ],
    category: 'structure',
  },

  subtitle_char_usage: {
    id: 'subtitle_char_usage',
    title: 'Subtitle Character Usage',
    shortDesc: 'Percentage of subtitle character limit used (iOS: 30 chars, Android: 80 chars)',
    longDesc: 'Subtitle character usage measures how well you\'re leveraging subtitle space for additional keyword coverage. iOS allows 30 characters (same as title), Android allows 80 (much more room). The subtitle is your second-most valuable SEO asset after the title. Aim for 85-95% usage to maximize coverage while maintaining readability.',
    whatItMeans: {
      high: 'Great subtitle optimization! You\'re maximizing this valuable SEO space.',
      medium: 'Good usage but could add more keywords to increase coverage.',
      low: 'Major wasted opportunity. Your subtitle is too short - add more keywords.',
    },
    howToImprove: [
      'iOS: Use 25-28 chars (83-93% of 30)',
      'Android: Use 68-76 chars (85-95% of 80)',
      'Add keywords NOT in title for incremental coverage',
      'Focus on discovery keywords over brand repetition',
      'Use subtitle to expand on title\'s core message',
    ],
    category: 'structure',
  },
};

// ============================================================================
// Other Chart Metrics (SemanticDensity, Severity, etc.)
// ============================================================================

export const OTHER_CHART_DEFINITIONS: Record<string, KpiDefinition> = {
  semantic_density: {
    id: 'semantic_density',
    title: 'Semantic Density',
    shortDesc: 'Ratio of high-value keywords to total tokens - measures keyword quality vs. filler',
    longDesc: 'Semantic density is the percentage of your metadata that consists of high-value, meaningful keywords versus filler, stopwords, and low-value modifiers. High semantic density (60%+) means most of your words are working hard for SEO. Low density means you\'re wasting space on generic terms. This is calculated by dividing high-value + medium-value tokens by total tokens.',
    whatItMeans: {
      high: 'Excellent keyword efficiency! Most of your words are meaningful and searchable.',
      medium: 'Good density but some room to trim filler and add better keywords.',
      low: 'Too much filler. You\'re wasting character space on generic, low-value words.',
    },
    howToImprove: [
      'Remove generic modifiers: "best", "top", "great"',
      'Replace vague terms with specific keywords: "40+ languages" not "many languages"',
      'Cut promotional fluff: "amazing", "ultimate", "perfect"',
      'Use concrete features instead of adjectives: "offline mode" not "great offline"',
      'Target 60-70% semantic density for optimal keyword:filler ratio',
    ],
    category: 'quality',
  },

  // Semantic token categories (used in TokenMixDonut)
  brand_token: {
    id: 'brand_token',
    title: 'Brand Tokens',
    shortDesc: 'Your app name, company name, and branded terms - essential for brand awareness',
    longDesc: 'Brand tokens include your app name, company name, and any branded terminology unique to your product. These are essential for users who already know you and are searching specifically for your app. However, over-indexing on brand (>30% of tokens) limits organic discovery. Aim for 10-25% brand tokens - enough for recognition without sacrificing discovery keywords.',
    whatItMeans: {
      high: 'Too much brand repetition! You\'re limiting organic discovery potential.',
      medium: 'Balanced brand presence. Good mix of identity and discovery keywords.',
      low: 'Under-branded. Add your app name for brand recognition and attribution.',
    },
    howToImprove: [
      'Limit brand mentions to 1-2 times in title/subtitle',
      'Use brand strategically: "Duolingo Spanish" not "Duolingo by Duolingo"',
      'Save brand-heavy content for screenshots and videos',
      'Balance brand with category keywords for discovery',
      'Target 10-25% brand ratio (1-2 mentions across all metadata)',
    ],
    category: 'quality',
  },

  category_token: {
    id: 'category_token',
    title: 'Category Tokens',
    shortDesc: 'Category-defining keywords that establish what type of app you are',
    longDesc: 'Category tokens are the fundamental keywords that define what your app does and what category it belongs to. For language apps: "language", "translator", "dictionary". For fitness apps: "workout", "fitness", "exercise". These are must-have terms that help users find apps like yours. They typically have high search volume and are essential for organic discovery.',
    whatItMeans: {
      high: 'Excellent category coverage! Users can easily identify what your app does.',
      medium: 'Good category keyword usage but could add more defining terms.',
      low: 'Weak category presence. Add more keywords that define your app type.',
    },
    howToImprove: [
      'Include primary category keyword: "language app", "fitness tracker"',
      'Add subcategory terms: "meditation", "HIIT", "vocabulary builder"',
      'Use industry-standard terminology users search for',
      'Include related category terms: "courses", "lessons", "training"',
      'Target 20-30% category tokens for strong categorization',
    ],
    category: 'coverage',
  },

  learning_token: {
    id: 'learning_token',
    title: 'Learning/Informational Tokens',
    shortDesc: 'Discovery keywords for users in research/learning mode',
    longDesc: 'Learning tokens attract users who are in discovery mode - researching options, learning about solutions, exploring alternatives. These include informational verbs (learn, discover, explore, understand), question words (how, what, why), and educational terms (guide, tutorial, tips). Critical for top-of-funnel discovery and organic growth.',
    whatItMeans: {
      high: 'Strong discovery potential! You\'re attracting users early in their journey.',
      medium: 'Some learning keywords present but could expand for more discovery.',
      low: 'Weak discovery language. Add informational keywords to attract new users.',
    },
    howToImprove: [
      'Add learning verbs: "learn", "discover", "explore", "master"',
      'Include question-based terms: "how to", "what is", "guide to"',
      'Use educational nouns: "tutorial", "guide", "tips", "lessons"',
      'Add exploratory language: "try", "start", "begin", "practice"',
      'Target 15-25% learning tokens for strong top-of-funnel discovery',
    ],
    category: 'intent',
  },

  outcome_token: {
    id: 'outcome_token',
    title: 'Outcome Tokens',
    shortDesc: 'Goal-oriented keywords that emphasize results and transformation',
    longDesc: 'Outcome tokens speak to user goals, desired results, and transformations. These are high-intent keywords that attract users ready to commit. Examples: "fluency", "mastery", "weight loss", "stress relief", "productivity". They answer "what will I achieve?" and convert well because they align with user motivation.',
    whatItMeans: {
      high: 'Excellent outcome messaging! You\'re speaking directly to user goals.',
      medium: 'Some outcome language but could emphasize results more strongly.',
      low: 'Weak outcome focus. Add goal-oriented keywords that promise transformation.',
    },
    howToImprove: [
      'Add achievement terms: "fluency", "mastery", "success", "results"',
      'Include transformation keywords: "improve", "boost", "enhance", "achieve"',
      'Use problem-solution language: "relief", "recovery", "growth"',
      'Add quantifiable outcomes: "30-day transformation", "5-minute workouts"',
      'Target 10-20% outcome tokens for strong value proposition',
    ],
    category: 'intent',
  },

  filler_token: {
    id: 'filler_token',
    title: 'Filler Tokens',
    shortDesc: 'Generic modifiers and fluff words that waste space - minimize these',
    longDesc: 'Filler tokens are generic superlatives (best, top, great), temporal modifiers (new, latest), and promotional fluff (amazing, ultimate, perfect). These provide no SEO value, don\'t help users find you, waste precious character space, and make metadata look spammy. They should be ruthlessly eliminated in favor of specific, searchable keywords. Target <10% filler.',
    whatItMeans: {
      high: 'Too much fluff! You\'re wasting space on generic words instead of real keywords.',
      medium: 'Some filler present. Clean up to make room for better keywords.',
      low: 'Minimal filler - excellent! You\'re using space efficiently for meaningful keywords.',
    },
    howToImprove: [
      'Remove "best", "top", "great", "amazing", "awesome"',
      'Cut "new", "latest", "modern", "innovative", "revolutionary"',
      'Eliminate "premium", "pro", "ultimate", "perfect", "incredible"',
      'Replace adjectives with concrete features: "offline mode" not "great offline"',
      'Target <10% filler tokens - every word should earn its place',
    ],
    category: 'quality',
  },

  duplicate_token: {
    id: 'duplicate_token',
    title: 'Duplicate Tokens',
    shortDesc: 'Repeated keywords that provide no incremental SEO value',
    longDesc: 'Duplicate tokens are keywords repeated across title, subtitle, and description. While some repetition can reinforce important terms, excessive duplication wastes character space that could be used for new keyword coverage. The app store algorithm doesn\'t give extra credit for repetition - it only indexes each unique keyword once. Minimize duplicates to maximize keyword diversity.',
    whatItMeans: {
      high: 'Excessive repetition! You\'re wasting space by repeating the same keywords.',
      medium: 'Some duplication present. Consider replacing repeats with new keywords.',
      low: 'Great keyword diversity! You\'re maximizing coverage with unique terms.',
    },
    howToImprove: [
      'Audit for repeated keywords across title/subtitle/description',
      'Replace duplicate keywords with synonyms or related terms',
      'Use title for primary keywords, subtitle for secondary coverage',
      'Description should expand vocabulary, not repeat title/subtitle',
      'Target <15% duplication - prioritize keyword diversity',
    ],
    category: 'coverage',
  },
};

// ============================================================================
// Unified Lookup Function
// ============================================================================

/**
 * Get definition from any registry
 */
export function getDefinition(metricId: string): KpiDefinition | undefined {
  return (
    METADATA_DIMENSION_DEFINITIONS[metricId] ||
    INTENT_TYPE_DEFINITIONS[metricId] ||
    TOKEN_TYPE_DEFINITIONS[metricId] ||
    CHARACTER_LIMIT_DEFINITIONS[metricId] ||
    OTHER_CHART_DEFINITIONS[metricId]
  );
}
