/**
 * Enhanced Feature System Constants
 * Extends the original features with enterprise-grade feature management
 */

export const FEATURE_CATEGORIES = {
  PERFORMANCE_INTELLIGENCE: 'performance_intelligence',
  AI_COMMAND_CENTER: 'ai_command_center', 
  GROWTH_ACCELERATORS: 'growth_accelerators',
  CONTROL_CENTER: 'control_center',
  ACCOUNT: 'account'
} as const;

export const PLATFORM_FEATURES_ENHANCED = {
  // Performance Intelligence
  EXECUTIVE_DASHBOARD: 'executive_dashboard',
  ANALYTICS: 'analytics',
  CONVERSION_INTELLIGENCE: 'conversion_intelligence',

  // AI Command Center  
  ASO_AI_HUB: 'aso_ai_hub',
  CHATGPT_VISIBILITY_AUDIT: 'chatgpt_visibility_audit',

  // Growth Accelerators
  STRATEGY_BRAIN: 'strategy_brain',
  METADATA_GENERATOR: 'metadata_generator',
  OPPORTUNITY_SCANNER: 'opportunity_scanner',
  FEATURE_MAXIMIZER: 'feature_maximizer',
  CREATIVE_REVIEW: 'creative_review',
  WEB_RANK_APPS: 'web_rank_apps',
  KEYWORD_INTELLIGENCE: 'keyword_intelligence',
  COMPETITIVE_INTELLIGENCE: 'competitive_intelligence',
  REVIEW_MANAGEMENT: 'review_management',
  REVIEW_MANAGEMENT_V2: 'review_management_v2',

  // Control Center
  APP_INTELLIGENCE: 'app_intelligence',
  PORTFOLIO_MANAGER: 'portfolio_manager',
  ADMIN_PANEL: 'admin_panel',

  // Account
  PROFILE_MANAGEMENT: 'profile_management',
  PREFERENCES: 'preferences'
} as const;

export type EnhancedPlatformFeature = typeof PLATFORM_FEATURES_ENHANCED[keyof typeof PLATFORM_FEATURES_ENHANCED];

export const FEATURE_DISPLAY_NAMES = {
  [PLATFORM_FEATURES_ENHANCED.EXECUTIVE_DASHBOARD]: 'Executive Dashboard',
  [PLATFORM_FEATURES_ENHANCED.ANALYTICS]: 'Analytics',
  [PLATFORM_FEATURES_ENHANCED.CONVERSION_INTELLIGENCE]: 'Conversion Intelligence',
  [PLATFORM_FEATURES_ENHANCED.ASO_AI_HUB]: 'Strategic Audit Engine',
  [PLATFORM_FEATURES_ENHANCED.CHATGPT_VISIBILITY_AUDIT]: 'AI Visibility Optimizer',
  [PLATFORM_FEATURES_ENHANCED.STRATEGY_BRAIN]: 'Strategy Brain',
  [PLATFORM_FEATURES_ENHANCED.METADATA_GENERATOR]: 'Metadata Optimizer',
  [PLATFORM_FEATURES_ENHANCED.OPPORTUNITY_SCANNER]: 'Opportunity Scanner',
  [PLATFORM_FEATURES_ENHANCED.FEATURE_MAXIMIZER]: 'Feature Maximizer',
  [PLATFORM_FEATURES_ENHANCED.CREATIVE_REVIEW]: 'Creative Analysis',
  [PLATFORM_FEATURES_ENHANCED.WEB_RANK_APPS]: 'Web Rank (Apps)',
  [PLATFORM_FEATURES_ENHANCED.KEYWORD_INTELLIGENCE]: 'Keyword Intelligence',
  [PLATFORM_FEATURES_ENHANCED.COMPETITIVE_INTELLIGENCE]: 'Competitor Overview',
  [PLATFORM_FEATURES_ENHANCED.REVIEW_MANAGEMENT]: 'Review Management',
  [PLATFORM_FEATURES_ENHANCED.REVIEW_MANAGEMENT_V2]: 'Review Management v2',
  [PLATFORM_FEATURES_ENHANCED.APP_INTELLIGENCE]: 'App Intelligence',
  [PLATFORM_FEATURES_ENHANCED.PORTFOLIO_MANAGER]: 'Portfolio Manager',
  [PLATFORM_FEATURES_ENHANCED.ADMIN_PANEL]: 'System Control',
  [PLATFORM_FEATURES_ENHANCED.PROFILE_MANAGEMENT]: 'Profile',
  [PLATFORM_FEATURES_ENHANCED.PREFERENCES]: 'Preferences'
} as const;

export const CATEGORY_DISPLAY_NAMES = {
  [FEATURE_CATEGORIES.PERFORMANCE_INTELLIGENCE]: 'Performance Intelligence',
  [FEATURE_CATEGORIES.AI_COMMAND_CENTER]: 'AI Command Center',
  [FEATURE_CATEGORIES.GROWTH_ACCELERATORS]: 'Growth Accelerators',
  [FEATURE_CATEGORIES.CONTROL_CENTER]: 'Control Center',
  [FEATURE_CATEGORIES.ACCOUNT]: 'Account'
} as const;

// Feature to category mapping
export const FEATURE_CATEGORY_MAP = {
  [PLATFORM_FEATURES_ENHANCED.EXECUTIVE_DASHBOARD]: FEATURE_CATEGORIES.PERFORMANCE_INTELLIGENCE,
  [PLATFORM_FEATURES_ENHANCED.ANALYTICS]: FEATURE_CATEGORIES.PERFORMANCE_INTELLIGENCE,
  [PLATFORM_FEATURES_ENHANCED.CONVERSION_INTELLIGENCE]: FEATURE_CATEGORIES.PERFORMANCE_INTELLIGENCE,
  [PLATFORM_FEATURES_ENHANCED.ASO_AI_HUB]: FEATURE_CATEGORIES.AI_COMMAND_CENTER,
  [PLATFORM_FEATURES_ENHANCED.CHATGPT_VISIBILITY_AUDIT]: FEATURE_CATEGORIES.AI_COMMAND_CENTER,
  [PLATFORM_FEATURES_ENHANCED.STRATEGY_BRAIN]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.METADATA_GENERATOR]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.OPPORTUNITY_SCANNER]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.FEATURE_MAXIMIZER]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.CREATIVE_REVIEW]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.WEB_RANK_APPS]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.KEYWORD_INTELLIGENCE]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.COMPETITIVE_INTELLIGENCE]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.REVIEW_MANAGEMENT]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.REVIEW_MANAGEMENT_V2]: FEATURE_CATEGORIES.GROWTH_ACCELERATORS,
  [PLATFORM_FEATURES_ENHANCED.APP_INTELLIGENCE]: FEATURE_CATEGORIES.CONTROL_CENTER,
  [PLATFORM_FEATURES_ENHANCED.PORTFOLIO_MANAGER]: FEATURE_CATEGORIES.CONTROL_CENTER,
  [PLATFORM_FEATURES_ENHANCED.ADMIN_PANEL]: FEATURE_CATEGORIES.CONTROL_CENTER,
  [PLATFORM_FEATURES_ENHANCED.PROFILE_MANAGEMENT]: FEATURE_CATEGORIES.ACCOUNT,
  [PLATFORM_FEATURES_ENHANCED.PREFERENCES]: FEATURE_CATEGORIES.ACCOUNT
} as const;