/**
 * COMPETITIVE METRICS TYPES
 * TypeScript interfaces for Phase 1 competitive analysis enhancement
 * Database tables: competitor_metrics_snapshots, feature_sentiment_analysis
 */

// ============================================================================
// DATABASE TABLE TYPES
// ============================================================================

/**
 * Competitor Metrics Snapshot
 * Periodic snapshots of competitor metrics for trend analysis
 */
export interface CompetitorMetricsSnapshot {
  id: string;
  organization_id: string;
  target_app_id: string;
  competitor_app_store_id: string;

  // Snapshot metadata
  snapshot_date: string; // ISO date string
  country: string;

  // Core metrics
  rating: number | null;
  review_count: number | null;
  review_velocity_7d: number | null;
  review_velocity_30d: number | null;

  // Sentiment metrics (percentages)
  sentiment_positive_pct: number | null;
  sentiment_neutral_pct: number | null;
  sentiment_negative_pct: number | null;
  avg_sentiment_score: number | null; // -1 to 1

  // Issue metrics
  issue_frequency_per_100: number | null;
  top_issues: TopIssue[] | null;

  // Tracking
  created_at: string;
}

export interface TopIssue {
  issue: string;
  frequency: number;
  severity: 'critical' | 'major' | 'minor';
}

/**
 * Feature Sentiment Analysis
 * Feature-level sentiment for heatmap visualization
 */
export interface FeatureSentimentAnalysis {
  id: string;
  organization_id: string;
  comparison_id: string | null;

  // App identification
  app_store_id: string;
  app_name: string;
  country: string;

  // Feature identification
  feature_name: string;
  feature_category: 'UX' | 'Performance' | 'Functionality' | 'Support' | 'Content' | null;

  // Sentiment breakdown
  mention_count: number;
  sentiment_score: number | null; // -1 to 1
  positive_mentions: number;
  neutral_mentions: number;
  negative_mentions: number;

  // Demand scoring
  demand_score: number | null; // 0-100
  demand_level: 'high' | 'medium' | 'low' | null;

  // Competitive context
  is_gap: boolean;
  competitors_with_feature: string[] | null;
  avg_competitor_sentiment: number | null;

  // Evidence
  sample_reviews: SampleReview[] | null;

  // Tracking
  analyzed_at: string;
}

export interface SampleReview {
  text: string;
  rating: number;
  date: string;
}

// ============================================================================
// VIEW TYPES
// ============================================================================

/**
 * Competitor Benchmark Matrix
 * Latest metrics with percentile rankings
 */
export interface CompetitorBenchmarkMatrix {
  organization_id: string;
  target_app_id: string;
  target_app_name: string;
  competitor_app_store_id: string;
  competitor_app_name: string;
  country: string;

  // Metrics
  rating: number | null;
  review_count: number | null;
  review_velocity_7d: number | null;
  review_velocity_30d: number | null;
  sentiment_positive_pct: number | null;
  avg_sentiment_score: number | null;
  issue_frequency_per_100: number | null;

  // Percentile ranks (0-1)
  rating_percentile: number | null;
  sentiment_percentile: number | null;
  velocity_percentile: number | null;

  snapshot_date: string;
  created_at: string;
}

/**
 * Feature Gap Opportunity
 * Ranked feature gaps with opportunity scores
 */
export interface FeatureGapOpportunity {
  organization_id: string;
  feature_name: string;
  feature_category: string | null;
  mention_count: number;
  sentiment_score: number | null;
  demand_score: number | null;
  demand_level: 'high' | 'medium' | 'low' | null;
  competitor_count: number;
  avg_competitor_sentiment: number | null;
  opportunity_score: number; // 0-100 calculated
  country: string;
  analyzed_at: string;
  sample_reviews: SampleReview[] | null;
}

// ============================================================================
// FUNCTION RETURN TYPES
// ============================================================================

/**
 * Competitive Summary
 * Generated by generate_competitive_summary() function
 */
export interface CompetitiveSummary {
  position: 'leading' | 'competitive' | 'lagging';
  rating_delta_pct: number;
  sentiment_delta_pct: number;
  review_delta_pct: number;
  velocity_delta_pct: number;
  primary_rating: number | null;
  competitor_avg_rating: number | null;
  primary_sentiment: number | null;
  competitor_avg_sentiment: number | null;
  top_feature_gap: string | null;
  top_gap_opportunity_score: number | null;
  summary_text: string;
  generated_at: string;
}

// ============================================================================
// ENHANCED TYPES (for UI components)
// ============================================================================

/**
 * Benchmark Metric Row
 * For BenchmarkOverviewTable component
 */
export interface BenchmarkMetricRow {
  metric: string;
  icon: string;
  yourValue: number | string;
  competitorAvg: number | string;
  topCompetitor: number | string;
  delta: number;
  deltaFormatted: string; // e.g., "-47%"
  unit: 'rating' | 'count' | 'percent' | 'velocity';
  direction: 'higher_better' | 'lower_better';
  status: 'good' | 'neutral' | 'bad';
}

/**
 * Feature Sentiment Heatmap Data
 * For FeatureSentimentHeatmap component
 */
export interface FeatureSentimentHeatmapData {
  features: string[]; // Row labels
  apps: HeatmapApp[]; // Column data
  matrix: HeatmapCell[][];
}

export interface HeatmapApp {
  appId: string;
  appName: string;
  isPrimary: boolean;
}

export interface HeatmapCell {
  featureName: string;
  appId: string;
  sentiment: number | null; // -1 to 1 or null if missing
  mentions: number;
  isMissing: boolean;
  sampleReviews?: SampleReview[];
}

/**
 * Review Volume & Velocity Data
 * For ReviewVolumeVelocityCharts component
 */
export interface ReviewVolumeVelocityData {
  apps: VolumeVelocityApp[];
  velocityHistory: VelocityHistoryPoint[];
}

export interface VolumeVelocityApp {
  appId: string;
  appName: string;
  totalReviews: number;
  weeklyVelocity: number;
  isPrimary: boolean;
}

export interface VelocityHistoryPoint {
  week: string; // ISO date of week start
  velocities: Record<string, number>; // { appId: velocity }
}

/**
 * Enhanced Competitive Intelligence
 * Extension of existing CompetitiveIntelligence type
 */
export interface EnhancedCompetitiveIntelligence {
  // Existing fields (from competitor-review-intelligence.service.ts)
  primaryApp: any;
  competitors: any[];
  featureGaps: any[];
  opportunities: any[];
  strengths: any[];
  threats: any[];
  metrics: any;
  summary: any;

  // New fields (Phase 1)
  benchmarkMatrix: CompetitorBenchmarkMatrix[];
  featureGapOpportunities: FeatureGapOpportunity[];
  competitiveSummary: CompetitiveSummary;
  heatmapData: FeatureSentimentHeatmapData;
  volumeVelocityData: ReviewVolumeVelocityData;
}
